[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first'

[fuzz]
runs = 1000

[profile.default]
solc = '0.8.16'
src = 'solidity'
test = 'solidity/test'
out = 'out'
libs = ['lib']
optimizer_runs = 10_000

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
rinkeby = "${RINKEBY_RPC}"
